task2

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -10,9 +10,26 @@
 # scp must transfer the file to the user home directory ~/
 # Strict host key checking must be disabled when using scp
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign command line arguments to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+# Disable strict host key checking
+SCP_COMMAND="scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/"
+
+# Execute the scp command
+$SCP_COMMAND
+
+# Check the exit status of scp
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "File transfer failed."
 fi
